### ISSUE TITLE
Can’t make «class ocid» id «data optr000000004574727565000000» into type integer. (error -1700)

### ISSUE THREAD

**Issue by mjlthomas** [pmbuko/ADPassMon#10]
Menu item is not loading despite ADPassMon running in Activity Monitor, behavior seen on both v1.11.0 and v1.11.0-b2 on OS 10.10.4. Issue does not present in v1.10.3

7/13/15 2:19:38.413 PM ADPassMon[28707]: Running on OS 10.10.x
7/13/15 2:19:38.413 PM ADPassMon[28707]: Testing Universal Access settings…
7/13/15 2:19:38.420 PM ADPassMon[28707]: *** -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Can’t make «class ocid» id «data optr000000004574727565000000» into type integer. (error -1700)

**Comment by pmbuko** [comment]
I'm not quite sure where this error is occuring, so I have added a little more detailed logging. Please [download this build (v1.11.0b3)](https://dl.dropboxusercontent.com/u/3967964/ADPassMon.v1.11.0b3.zip) and let me know what the logs say this time.

**Comment by mjlthomas** [comment]
Error is still present in the console log however ADPassMon does now complete launching. I did see the prompt to set accessibility and it immediately checked kerbminder for ticket status and promoted to request when it found none. Neither of these occurred on launch before, I like the changes.

console log follows:
7/14/15 9:42:25.466 AM ADPassMon[1775]: Running on OS 10.10.x
7/14/15 9:42:25.467 AM ADPassMon[1775]: Testing Universal Access settings…
7/14/15 9:42:36.200 AM ADPassMon[1775]:   Prompting for password
7/14/15 9:42:40.438 AM ADPassMon[1775]:   Enabled
7/14/15 9:42:40.458 AM ADPassMon[1775]: Loading prefs...
7/14/15 9:42:40.583 AM ADPassMon[1775]: Testing if password can expire…
7/14/15 9:42:40.619 AM ADPassMon[1775]:   Password does expire.
7/14/15 9:42:40.619 AM ADPassMon[1775]: Testing for Kerberos ticket presence…
7/14/15 9:42:40.631 AM ADPassMon[1775]:   No ticket found
7/14/15 9:42:47.318 AM ADPassMon[1775]:   Ticket acquired
7/14/15 9:42:48.660 AM ADPassMon[1775]: Testing for Kerberos ticket presence…
7/14/15 9:42:48.689 AM ADPassMon[1775]:   Ticket found and renewed
7/14/15 9:42:48.689 AM ADPassMon[1775]: Loading prefs...
7/14/15 9:42:48.711 AM ADPassMon[1775]: Starting auto process…
7/14/15 9:42:48.742 AM ADPassMon[1775]:   myDomain: ldcint.com
7/14/15 9:42:48.742 AM ADPassMon[1775]:   myADLDAP: dc102-aws.ldcint.com.
7/14/15 9:42:48.779 AM ADPassMon[1775]:   Got expireDateUnix: 1444432297
7/14/15 9:42:48.814 AM ADPassMon[1775]:   Got expireDateUnix: 1444432297
7/14/15 9:42:48.814 AM ADPassMon[1775]:   Using msDS method
7/14/15 9:42:48.822 AM ADPassMon[1775]:     daysUntilExp: 87.270011574074
7/14/15 9:42:48.822 AM ADPassMon[1775]:     daysUntilExpNice: 87
7/14/15 9:42:48.827 AM ADPassMon[1775]: *** -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Can’t make «class ocid» id «data optr000000004574727565000000» into type integer. (error -1700)

**Comment by mjlthomas** [comment]
I assume:
7/14/15 9:50:10.376 AM universalAccessAuthWarn[1842]: AccessibilityAPI: pid 1850, is not allowed to access the accessibility API. Path: /usr/local/bin/ADPassMon.app/Contents/MacOS/ADPassMon (Leaf request from pid 1836 Path: /System/Library/CoreServices/System Events.app/Contents/MacOS/System Events)
7/14/15 9:50:10.380 AM ADPassMon[1850]: *** -[ADPassMonAppDelegate changePassword:]: System Preferences got an error: Can’t continue errorOut_. (error -1708)

Is due to it being a test version?

**Comment by pmbuko** [comment]
The 'universalAccessAuthWarn' entry should only occur if ADPassMon isn't in the list of apps allowed to control the GUI. From the logs, it looks like you went through the process of adding it. Since it says "Prompting for password" and then "Enabled".

You can check it visually in SysPrefs > Security&Privacy > Privacy tab > Accessibility

**Comment by mjlthomas** [comment]
I visually confirmed it was there.

The setting was pre-existing to the install, purging the entry (via sqlite)
then relaunching appears to clear the issue. I'm assuming since it prompted
it detected that it was not set correctly. Perhaps check if there is a old
/bad/ entry first, purge then set?

-- 

*Michael Thomas*
Manager of Internal Systems - lynda.com
Technology Operations - lynda.com


818.264.8415
mithomas@linkedin.com
linkedin.com/in/michaeljlthomas/

**Comment by pmbuko** [comment]
I think purging ADPassMon's prefs could have also fixed it. I do this step every time I test a new version and did not run into problem. I also do not see the "Can’t make «class ocid»" error so I'm having trouble tracking it down. Can you try purging your prefs using the Reset tab in ADPassMon, and then quit and restart the app to see if that helps?

**Comment by mjlthomas** [comment]
Original issue also seems that have go away.. perhaps related to the same bad entry, I'll test a bit more.

The original entry was added via sqllite manually, so that ckreq in the access table is null, perhaps that was the issue since it was not done in the proper manner, with your code change that method is no longer required.

**Comment by pmbuko** [comment]
Ok. I'll roll these updates onto a release and close the issue.

**Comment by pmbuko** [comment]
Closed with [v1.11.0-final](https://github.com/pmbuko/ADPassMon/releases/tag/v1.11.0-final)
