### ISSUE TITLE
Support local user with different username

### ISSUE THREAD

**Issue by gthb** [pmbuko/ADPassMon#3]
I'm accessing domain resources over VPN from a local user account that isn't domain-associated (yet) and doesn't have the same username as my AD user. (Recently joined a company, this is the interim setup.)

ADPassMon doesn't offer to set a username. But it does offer to refresh a kerberos ticket, and when I do so and enter my password, it comes up with an expiration time in the year when Hamlet is believed to have been first performed, and a password expiry timeout of -151180 days.

![image](https://cloud.githubusercontent.com/assets/153580/6439334/b1bda2f0-c0c9-11e4-9329-bae1d5be640d.png)

**Comment by gthb** [comment]
Oh, just noticed that this issue is known for a long time now, in comments from 2011 in https://yourmacguy.wordpress.com/adpassmon/ — still worth registering it here, I guess. Will ADPassMon still work if it just sends the correct domain account name, or must the user account be domain-associated?

**Comment by pmbuko** [comment]
I'm actually preparing to hand over the reins of ADPassMon development to [macmule](https://github.com/macmule/ADPassMon]). He has a fork in active development. I'm pretty much only doing bigfixes at this point, and yours is a new feature request.

**Comment by gthb** [comment]
OK — I'm closing this and commenting on https://github.com/macmule/ADPassMon/issues/4 then. Thanks!
