### ISSUE TITLE
myLDAP does not work in all environments

### ISSUE THREAD

**Issue by patgmac** [pmbuko/ADPassMon#6]
The method used to determine the value for myLDAP assumes that the DNS server used is also an LDAP server. In our environment (which I admit is not ideal), DNS and AD/LDAP are separate. So ADpassMon is trying to do an ldapsearch to a DNS server. This DNS sever does contain SRV records, so perhaps finding a DC address with an SRV lookup would be more accurate?

When I run ADpassMon, there is a long delay (about 3 minutes) before the menu can be clicked. And any time I make a pref change, there is also a long delay. Also, when I try to set a manual password age discovery, it reverts back to Auto (even if configured from a profile or defaults write). 

If I modify ADPassMonAppDelgate.applescript so that myLDAP is set to a known LDAP IP, the delay goes away and I can manually set the password age discovery. 

However, my menu_title is set to -287d. 

defaults read org.pmbuko.ADPassMon
{
    expireAge = 365;
    isBehaviour2Enabled = 1;
    "menu_title" = "[-287d]";
    pwdSetDate = "15944.56";
    selectedBehaviour = 2;
    selectedMethod = 1;
    tooltip = "Password expires on Wednesday, August 27, 2014 at 9:26:25 AM";
    warningDays = 14;
}

I'm not sure if its' inability to generate the correct expiration is site specific. We do not allow AD password changes, instead use a website to handle password changes. So I'm not sure if there's an attribute missing from our AD to get his to work. However, the date in the tooltip above does correctly show when this account last changed their password. So would think adding 365 days to that should give the correct value?

Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]: selectedMethod: 365
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]: Starting manual process…
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   Found expireAge in plist: 365
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   New pwdSetDate (15944.56)
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   ≥ plist value (1.594456E+4) so we use it
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExp: -287.2757
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExpNice: -287
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   expirationDate: Wednesday, August 27, 2014 at 9:26:26 AM
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]: Behaviour 2 enabled...
Jun 10 16:03:26 COL-PGALLA2-01a ADPassMon[65367]:   Skipping Keychain Lock state check...
	Domain (org.pmbuko.ADPassMon) not found.
Jun 10 16:03:28 COL-PGALLA2-01a ADPassMon[65367]: *** -[ADPassMonAppDelegate revertDefaults:]: 2015-06-10 16:03:28.774 defaults[78609:1501747] 
	Domain (org.pmbuko.ADPassMon) not found.
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]: selectedMethod: 365
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]: Starting manual process…
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   Found expireAge in plist: 365
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   New pwdSetDate (15944.56)
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   will be saved to plist.
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExp: -287.2758
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExpNice: -287
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   expirationDate: Wednesday, August 27, 2014 at 9:26:22 AM
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]: Behaviour 2 enabled...
Jun 10 16:03:31 COL-PGALLA2-01a ADPassMon[65367]:   Skipping Keychain Lock state check...
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]: Starting manual process…
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   Found expireAge in plist: 365
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   New pwdSetDate (15944.56)
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   ≥ plist value (1.594456E+4) so we use it
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExp: -287.2758
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   daysUntilExpNice: -287
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   expirationDate: Wednesday, August 27, 2014 at 9:26:28 AM
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]: Behaviour 2 enabled...
Jun 10 16:03:37 COL-PGALLA2-01a ADPassMon[65367]:   Skipping Keychain Lock state check...

**Comment by pmbuko** [comment]
Pat, you are correct. I made a big assumption about the DNS server also being the AD LDAP server. I can see from the British spelling of "behaviour" in the content of your plist that you are using Ben Toms' fork of ADPassMon. I would post this issue in that repo. Ben recently merged the changes I've made since he forked his version, so his will be the "master" version from here on out.

**Comment by patgmac** [comment]
Thanks Peter. I was posting the issue here at Ben's suggestion, we were chatting about this in the Slack channel. I don't think issues can be posted for forks. But either way, he knows this is here.

**Comment by pmbuko** [comment]
I had a crazy couple of weeks but things have started to settle down. I have an idea about how to fix it and will give it a shot.

-- Peter (from phone)

**Comment by pmbuko** [comment]
Pat, I've just released [v1.10.3](https://github.com/pmbuko/ADPassMon/releases) that uses the new AD lookup behavior. Give it a shot and let me know if that fixes it for you.
