### ISSUE TITLE
Manual field doesn't save

### ISSUE THREAD

**Issue by ftiff** [pmbuko/ADPassMon#9]
10.10.4 (14E46)
In preferences, if user changes the manual field and then click on "Apply changes", it reverts to Auto.
User needs to first do "TAB" after inputing value, then click on "Apply changes".

**Comment by pmbuko** [comment]
This bug has been on my list for a while.

**Comment by pmbuko** [comment]
[The pre-release](https://github.com/pmbuko/ADPassMon/releases/tag/1.11.0) I just posted addresses this issue.

**Comment by pmbuko** [comment]
Closed with [v1.11.0-final](https://github.com/pmbuko/ADPassMon/releases/tag/v1.11.0-final)
